const cabinData =[

    {
                "name": "A-frame in the Woods",
                "thumbnailURL": "./cabinAssets/chung-yee-tsang-1149219-unsplash.jpg",
                "sleeps": "8",
                "location": "New York",
                "propertytype": "woods",
                "neighbors": "none",
                "distance": "20 mins",
                "activities_1": "hiking",
                "activities_2": "",
                "activities_3": "",
                "features_1": "fire pit",
                "features_2": "wood burning stove",
                "features_3": "sauna",
                "url": "",
                "price":"135",
                "cabinType": "Cabin"
            },
            {
                "name": "Mountain Chalet",
                "thumbnailURL": "./cabinAssets/evan-leith-1150188-unsplash.jpg",
                "sleeps": "6",
                "location": "Boston",
                "propertytype": "mountain view",
                "neighbors": "none",
                "distance": "35 mins",
                "activities_1": "skiing",
                "activities_2": "",
                "activities_3": "",
                "features_1": "fire pit",
                "features_2": "wood burning stove",
                "features_3": "sauna",
                "url": "",
                "price":"175",
                "cabinType": "Log Cabin"
            },
            {
                "name": "Writer's Cabin",
                "thumbnailURL": "./cabinAssets/derek-sears-1364406-unsplash.jpg",
                "sleeps": "4",
                "location": "DC",
                "propertytype": "off the grid",
                "neighbors": "none",
                "distance": "60 mins",
                "activities_1": "trail running",
                "activities_2": "bike trails",
                "activities_3": "",
                "features_1": "fire pit",
                "features_2": "wood burning stove",
                "features_3": "sauna",
                "url": "",
                "price":"99",
                "cabinType": "A-Frame"
            },
            {
                "name": "Snowshoe Heaven",
                "thumbnailURL": "./cabinAssets/debra-warwick-1389956-unsplash.jpg",
                "sleeps": "12",
                "location": "Boston",
                "propertytype": "woods",
                "neighbors": "none",
                "distance": "backyard",
                "activities_1": "hiking",
                "activities_2": "snow shoeing",
                "activities_3": "skiing",
                "features_1": "fire pit",
                "features_2": "wood burning stove",
                "features_3": "sauna",
                "url": "",
                "price":"117",
                "cabinType": "Tent"
            },
            {
                "name": "Lakeside Cabin",
                "thumbnailURL": "./cabinAssets/damiano-baschiera-779294-unsplash.jpg",
                "sleeps": "5",
                "location": "New York",
                "propertytype": "lake",
                "neighbors": "in sight",
                "distance": "5 mins",
                "activities_1": "kayaking",
                "activities_2": "lake activities",
                "activities_3": "",
                "features_1": "fire pit",
                "features_2": "wood burning stove",
                "features_3": "sauna",
                "url": "",
                "price":"167",
                "cabinType": "Cabin"
            },
            {
                "name": "Getaway Cabin",
                "thumbnailURL": "./cabinAssets/dane-deaner-284387-unsplash.jpg",
                "sleeps": "4",
                "location": "DC",
                "propertytype": "off the grid",
                "neighbors": "none",
                "distance": "90 mins",
                "activities_1": "star gazing",
                "activities_2": "hiking",
                "activities_3": "walking trails",
                "features_1": "fire pit",
                "features_2": "wood burning stove",
                "features_3": "sauna",
                "url": "",
                "price":"103",
                "cabinType": "Log Cabin"
            },
            {
                "name": "Sleep Under the Stars",
                "thumbnailURL": "./cabinAssets/eric-ward-715294-unsplash.jpg",
                "sleeps": "8",
                "location": "Boston",
                "propertytype": "Dark Sky",
                "neighbors": "next door",
                "distance": "40 mins",
                "activities_1": "star gazing",
                "activities_2": "camping",
                "activities_3": "walking trails",
                "features_1": "fire pit",
                "features_2": "wood burning stove",
                "features_3": "sauna",
                "url": "",
                "price":"215",
                "cabinType": "Tent"
            },
            {
                "name": "A-frame On the Lake",
                "thumbnailURL": "./cabinAssets/ian-keefe-449093-unsplash (1).jpg",
                "sleeps": "2",
                "location": "New York",
                "propertytype": "Lake",
                "neighbors": "in sight",
                "distance": "backyard",
                "activities_1": "kayaking",
                "activities_2": "lake activities",
                "activities_3": "",
                "features_1": "fire pit",
                "features_2": "wood burning stove",
                "features_3": "sauna",
                "url": "",
                "price":"279",
                "cabinType": "A-Frame"
            },
            {
                "name": "Secret Chalet",
                "thumbnailURL": "./cabinAssets/daniil-silantev-307694-unsplash.jpg",
                "sleeps": "10",
                "location": "Boston",
                "propertytype": "woods",
                "neighbors": "none",
                "distance": "25 mins",
                "activities_1": "skiing",
                "activities_2": "snow shoeing",
                "activities_3": "",
                "features_1": "fire pit",
                "features_2": "wood burning stove",
                "features_3": "sauna",
                "url": "",
                "price":"139",
                "cabinType": "Cabin"
            },
            {
                "name": "Comfy Yurt",
                "thumbnailURL": "./cabinAssets/hugo-villegas-732351-unsplash.jpg",
                "sleeps": "4",
                "location": "New York",
                "propertytype": "off the grid",
                "neighbors": "none",
                "distance": "50 mins",
                "activities_1": "trail running",
                "activities_2": "bike trails",
                "activities_3": "",
                "features_1": "fire pit",
                "features_2": "wood burning stove",
                "features_3": "sauna",
                "url": "",
                "price":"85",
                "cabinType": "Yurt"
            },
            {
                "name": "See the Northern Lights",
                "thumbnailURL": "./cabinAssets/jonatan-pie-183185-unsplash.jpg",
                "sleeps": "6",
                "location": "Boston",
                "propertytype": "Dark Sky",
                "neighbors": "none",
                "distance": "20 mins",
                "activities_1": "star gazing",
                "activities_2": "",
                "activities_3": "",
                "features_1": "fire pit",
                "features_2": "wood burning stove",
                "features_3": "sauna",
                "url": "",
                "price":"140",
                "cabinType": "Tent"
            },
            {
                "name": "Mountain A-Frame",
                "thumbnailURL": "./cabinAssets/jonathan-ocampo-1268017-unsplash.jpg",
                "sleeps": "6",
                "location": "DC",
                "propertytype": "mountain view",
                "neighbors": "none",
                "distance": "35 mins",
                "activities_1": "hiking",
                "activities_2": "star gazing",
                "activities_3": "bike trails",
                "features_1": "fire pit",
                "features_2": "wood burning stove",
                "features_3": "sauna",
                "url": "",
                "price":"155",
                "cabinType": "A-Frame"
            },
            {
                "name": "Off the Grid A-Frame",
                "thumbnailURL": "./cabinAssets/kristin-ellis-649147-unsplash.jpg",
                "sleeps": "4",
                "location": "New York",
                "propertytype": "off the grid",
                "neighbors": "none",
                "distance": "20 mins",
                "activities_1": "camping",
                "activities_2": "walking trails",
                "activities_3": "",
                "features_1": "fire pit",
                "features_2": "wood burning stove",
                "features_3": "sauna",
                "url": "",
                "price":"129",
                "cabinType": "A-Frame"
            },
            {
                "name": "Yurt in the Trees",
                "thumbnailURL": "./cabinAssets/kyle-glenn-600172-unsplash.jpg",
                "sleeps": "4",
                "location": "DC",
                "propertytype": "woods",
                "neighbors": "none",
                "distance": "backyard",
                "activities_1": "star gazing",
                "activities_2": "bike trails",
                "activities_3": "hiking",
                "features_1": "fire pit",
                "features_2": "wood burning stove",
                "features_3": "sauna",
                "url": "",
                "price":"70",
                "cabinType": "Yurt"
            },
            {
                "name": "Cozy Green Mountain Cabin",
                "thumbnailURL": "./cabinAssets/marc-olivier-paquin-594494-unsplash.jpg",
                "sleeps": "5",
                "location": "Boston",
                "propertytype": "mountain view",
                "neighbors": "in sight",
                "distance": "5 mins",
                "activities_1": "skiing",
                "activities_2": "snow shoeing",
                "activities_3": "",
                "features_1": "fire pit",
                "features_2": "wood burning stove",
                "features_3": "sauna",
                "url": "",
                "price":"167",
                "cabinType": "Log Cabin"
            },
            {
                "name": "A-Frame on the River",
                "thumbnailURL": "./cabinAssets/nathan-dumlao-469594-unsplash.jpg",
                "sleeps": "4",
                "location": "DC",
                "propertytype": "Lake",
                "neighbors": "none",
                "distance": "90 mins",
                "activities_1": "kayaking",
                "activities_2": "",
                "activities_3": "",
                "features_1": "fire pit",
                "features_2": "wood burning stove",
                "features_3": "sauna",
                "url": "",
                "price":"164",
                "cabinType": "A-Frame"
            },
            {
                "name": "Cabin on the Mountainside",
                "thumbnailURL": "./cabinAssets/nigel-tadyanehondo-431362-unsplash.jpg",
                "sleeps": "8",
                "location": "New York",
                "propertytype": "mountain view",
                "neighbors": "next door",
                "distance": "40 mins",
                "activities_1": "tail running",
                "activities_2": "bike trails",
                "activities_3": "walking trails",
                "features_1": "fire pit",
                "features_2": "wood burning stove",
                "features_3": "sauna",
                "url": "",
                "price":"135",
                "cabinType": "Cabin"
            },
            {
                "name": "Hidden Yurts",
                "thumbnailURL": "./cabinAssets/pan-xiaozhen-424821-unsplash.jpg",
                "sleeps": "2",
                "location": "New York",
                "propertytype": "Off the Grid",
                "neighbors": "in sight",
                "distance": "backyard",
                "activities_1": "trail running",
                "activities_2": "bike trails",
                "activities_3": "star gazing",
                "features_1": "fire pit",
                "features_2": "wood burning stove",
                "features_3": "sauna",
                "url": "",
                "price":"79",
                "cabinType": "Yurt"
            },
            {
                "name": "Off the Grid Cabin",
                "thumbnailURL": "./cabinAssets/patrick-hodskins-764123-unsplash.jpg",
                "sleeps": "10",
                "location": "DC",
                "propertytype": "Off the Grid",
                "neighbors": "none",
                "distance": "25 mins",
                "activities_1": "hiking",
                "activities_2": "walking trails",
                "activities_3": "snow shoeing",
                "features_1": "fire pit",
                "features_2": "wood burning stove",
                "features_3": "sauna",
                "url": "",
                "price":"110",
                "cabinType": "A-Frame"
            },
            {
                "name": "Peace and Quiet Cabin",
                "thumbnailURL": "./cabinAssets/ryan-james-christopher-237247-unsplash.jpg",
                "sleeps": "4",
                "location": "New York",
                "propertytype": "mountain view",
                "neighbors": "none",
                "distance": "50 mins",
                "activities_1": "camping",
                "activities_2": "bike trails",
                "activities_3": "",
                "features_1": "fire pit",
                "features_2": "wood burning stove",
                "features_3": "sauna",
                "url": "",
                "price":"125",
                "cabinType": "Log Cabin"
            },{
                "name": "Middle of Nowhere",
                "thumbnailURL": "./cabinAssets/samuel-scrimshaw-101118-unsplash.jpg",
                "sleeps": "8",
                "location": "Boston",
                "propertytype": "Dark Sky",
                "neighbors": "none",
                "distance": "20 mins",
                "activities_1": "hiking",
                "activities_2": "trail running",
                "activities_3": "",
                "features_1": "fire pit",
                "features_2": "wood burning stove",
                "features_3": "sauna",
                "url": "",
                "price":"97",
                "cabinType": "A-Frame"
            },
            {
                "name": "The Artist's Retreat",
                "thumbnailURL": "./cabinAssets/thomas-layland-340828-unsplash.jpg",
                "sleeps": "6",
                "location": "Boston",
                "propertytype": "Dark Sky",
                "neighbors": "none",
                "distance": "35 mins",
                "activities_1": "star gazing",
                "activities_2": "camping",
                "activities_3": "",
                "features_1": "fire pit",
                "features_2": "wood burning stove",
                "features_3": "sauna",
                "url": "",
                "price":"99",
                "cabinType": "Tent"
            },
            {
                "name": "Private Late Retreat",
                "thumbnailURL": "./cabinAssets/wolfgang-lutz-26514-unsplash.jpg",
                "sleeps": "10",
                "location": "New York",
                "propertytype": "Lake",
                "neighbors": "none",
                "distance": "60 mins",
                "activities_1": "lake activities",
                "activities_2": "kayaking",
                "activities_3": "",
                "features_1": "fire pit",
                "features_2": "wood burning stove",
                "features_3": "sauna",
                "url": "",
                "price":"295",
                "cabinType": "Cabin"
            },
            {
                "name": "Skier's Paradise",
                "thumbnailURL": "./cabinAssets/yunxi-shi-182363-unsplash.jpg",
                "sleeps": "12",
                "location": "Boston",
                "propertytype": "Mountain View",
                "neighbors": "none",
                "distance": "backyard",
                "activities_1": "hiking",
                "activities_2": "trail running",
                "activities_3": "skiing",
                "features_1": "fire pit",
                "features_2": "wood burning stove",
                "features_3": "sauna",
                "url": "",
                "price":"185",
                "cabinType": "A-Frame"
            },
            
    ]
    
    export default cabinData;